import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Locale = "zh-CN" | "en-US";
const messages = {
  "zh-CN": {
    openFullscreen: "全屏打开", backToChat: "返回对话", currentSpace: "当前空间", live: "实时", connecting: "连接中", reconnect: "重新连接", create: "创建", allViews: "全部视图", pin: "固定", unpin: "取消固定", undoLayout: "撤销布局", selected: "已选", nodes: "个节点", emptySpace: "选择模板创建第一个语义空间", graphSnapshot: "语义空间快照", language: "EN",
    rename: "重命名", pinToTop: "固定到顶部", duplicate: "复制", defaultView: "默认视图", setDefault: "设为默认", moveToRecycle: "移到回收站", restore: "恢复", confirmDelete: "确认删除", deleteForever: "永久删除", deletes: "删除于", in30Days: "30 天后", moreActions: "更多操作", projectViews: "项目视图", closeViewLibrary: "关闭视图库", searchViews: "搜索视图…", fixed: "已固定", recent: "最近", noViewsMatch: "没有匹配的视图", recycleBin: "回收站", recycleHint: "删除的视图会保留 30 天。", newVisualView: "新建视觉视图",
    contentPreview: "内容预览", risk: "风险", agentChanges: "Agent 改动", updated: "已更新", relations: "条关系", layoutOps: "项布局操作", staleProposal: "此提案已过期，请让 Codex 基于当前画布重新生成。", reject: "拒绝", applyAll: "全部应用", taskStale: "任务已过期", taskStaleFallback: "任务运行期间画布发生了变化。", regenerate: "请让 Codex 基于当前画布重新生成。",
    canvasNavigation: "画布导航", zoomOut: "缩小", zoomLevel: "缩放比例", zoomIn: "放大", fitView: "适应全部内容", focusSelection: "聚焦选区", deleteNode: "删除节点", deleteNodes: "删除节点", toggleMinimap: "切换小地图", canvasAppearance: "画布外观", useLightCanvas: "使用浅色画布", useDarkCanvas: "使用深色画布",
    layoutPreview: "布局预览", nextOption: "下一个方案", apply: "应用", chooseProject: "选择项目", chooseProjectHint: "选择一个项目打开，或新建项目。", startNewProject: "新建项目", loadingProjects: "正在加载项目…", edit: "编辑", close: "关闭", undo: "撤销", newProject: "新建项目…", projectFromTemplate: "从模板创建项目", starterStructure: "创建初始结构和视觉视图", projectCurrentContent: "在不改变内容图谱的情况下创建新投影", article: "文章", sideEditor: "在侧边编辑器中写作", image: "图片", uploadPaste: "上传或粘贴", link: "链接", richPreview: "保存丰富预览", publicUrl: "公开网址", createLink: "创建链接",
    dragCanvas: "拖动画布", scrollPan: "滚动平移", scrollZoom: "⌘/Ctrl + 滚动缩放", shiftSelect: "按 Shift 多选", doubleClick: "双击打开", fixedLabel: "已固定", document: "文档", noData: "暂无数据", dismiss: "关闭通知", untitledArticle: "未命名文章", openToWrite: "打开后开始写作。", untitledImage: "未命名图片", untitledLink: "未命名链接", previewPending: "预览详情将在这里显示。",
    savingDraft: "正在保存…", unsavedChanges: "有未保存改动", newerVersion: "存在新版本", allSaved: "已全部保存", draftProtected: "你的草稿未被覆盖。", conflictHelp: "其他改动更新了此项目，请复制草稿或重新加载最新版本。", reloadLatest: "重新加载", title: "标题", semanticType: "语义类型", write: "编辑", preview: "预览", cover: "封面", attach: "附件", markdownFormatting: "Markdown 格式", heading: "标题格式", bold: "粗体", bulletList: "项目列表", writingPlaceholder: "从一个想法开始。Markdown 是内容事实源。", nothingWritten: "尚未写入内容。", characters: "个字符", saveNow: "立即保存",
    canvasConnecting: "正在连接 Weaver 画布", canvasConnectFailed: "Weaver 画布连接失败", canvasDuplicate: "此画布已在另一标签中打开", buildMismatch: "Widget 构建版本不一致", canvasDetached: "此画布已失去当前 Chat 的绑定", claimingHelp: "正在声明画布会话；视口将在连接后单独恢复。", duplicateHelp: "请使用已激活的 Weaver 标签；关闭本标签不会影响画布数据。", detachedHelp: "请从当前 Chat 重新打开 Weaver 画布。", errorCode: "错误码", retryHelp: "你可以立即重试。", buildMismatchHelp: "请使用 workspace 开发入口重新加载。",
    visualGallery: "视觉模板库", existingViews: "个已有视图", existingViewsHint: "打开已有视角，或明确创建另一个。", createProject: "创建项目", createAnotherView: "再创建一个视图…", createNewView: "创建新视图", schemaResetNotice: "旧数据已备份，并已创建新的 Weaver 空间。", backupLabel: "备份",
    visualSystem: "Weaver 视觉系统", createFromTemplate: "从视觉模板创建", visualTemplateHint: "从语义骨架、投影、布局与主题开始。", visualViewHint: "将同一内容投影为另一种结构，不改变图谱。", closeTemplateGallery: "关闭模板库", allVisuals: "全部视觉", searchTemplates: "搜索模板…", existing: "已有", backToTemplates: "返回模板", projectTitle: "项目名称", goal: "目标", goalPlaceholder: "你想探索什么？", scenePack: "场景包", viewName: "视图名称", viewNamePlaceholder: "为这个视角命名", open: "打开", selectTemplate: "选择模板", selectTemplateHint: "应用前检查结构、数据要求、布局和主题。", checkingData: "正在检查当前数据…", dataReady: "个节点可用于此视图", valuesMissing: "个必填值缺失", selectToValidate: "选择模板以校验当前数据", missing: "缺失", previewGenerated: "预览生成于 graph r",
    edgeStyleBar: "连线样式", lineStyleLabel: "线型", arrowsLabel: "箭头", routingLabel: "走向", solidLine: "实线", dashedLine: "虚线", noArrow: "无箭头", singleArrow: "单向箭头", doubleArrow: "双向箭头", straightLine: "直线", curvedLine: "曲线",
  },
  "en-US": {
    openFullscreen: "Open fullscreen", backToChat: "Back to chat", currentSpace: "Current space", live: "Live", connecting: "Connecting", reconnect: "Reconnect", create: "Create", allViews: "All Views", pin: "Pin", unpin: "Unpin", undoLayout: "Undo layout", selected: "Selected", nodes: "nodes", emptySpace: "Choose a template to create your first semantic space", graphSnapshot: "Semantic space snapshot", language: "中文",
    rename: "Rename", pinToTop: "Pin to top", duplicate: "Duplicate", defaultView: "Default View", setDefault: "Set as default", moveToRecycle: "Move to Recycle Bin", restore: "Restore", confirmDelete: "Confirm delete", deleteForever: "Delete forever", deletes: "deletes", in30Days: "in 30 days", moreActions: "More actions", projectViews: "Project Views", closeViewLibrary: "Close View Library", searchViews: "Search views…", fixed: "Fixed", recent: "Recent", noViewsMatch: "No Views match", recycleBin: "Recycle Bin", recycleHint: "Deleted Views stay here for 30 days.", newVisualView: "New visual view",
    contentPreview: "Content preview", risk: "risk", agentChanges: "Agent changes", updated: "updated", relations: "relations", layoutOps: "layout ops", staleProposal: "This proposal is stale. Ask Codex to regenerate it from the current canvas.", reject: "Reject", applyAll: "Apply all", taskStale: "Task is stale", taskStaleFallback: "The canvas changed while the task was running.", regenerate: "Ask Codex to regenerate it from the current canvas.",
    canvasNavigation: "Canvas navigation", zoomOut: "Zoom out", zoomLevel: "Zoom level", zoomIn: "Zoom in", fitView: "Fit whole view", focusSelection: "Focus selection", deleteNode: "Delete node", deleteNodes: "Delete nodes", toggleMinimap: "Toggle minimap", canvasAppearance: "Canvas appearance", useLightCanvas: "Use light canvas", useDarkCanvas: "Use dark canvas",
    layoutPreview: "Layout preview", nextOption: "Next option", apply: "Apply", chooseProject: "Choose a project", chooseProjectHint: "Pick a project to open, or start a new one.", startNewProject: "Start a new project", loadingProjects: "Loading projects…", edit: "Edit", close: "Close", undo: "Undo", newProject: "New project…", projectFromTemplate: "Project from template", starterStructure: "Create starter structure and visual", projectCurrentContent: "Project current content without changing it", article: "Article", sideEditor: "Write in the side editor", image: "Image", uploadPaste: "Upload or paste", link: "Link", richPreview: "Save a rich preview", publicUrl: "Public URL", createLink: "Create link",
    dragCanvas: "Drag canvas", scrollPan: "Scroll to pan", scrollZoom: "⌘/Ctrl + scroll to zoom", shiftSelect: "Shift to select", doubleClick: "double-click", fixedLabel: "fixed", document: "document", noData: "No data", dismiss: "Dismiss notification", untitledArticle: "Untitled article", openToWrite: "Open to begin writing.", untitledImage: "Untitled image", untitledLink: "Untitled link", previewPending: "Preview details will appear here.",
    savingDraft: "Saving draft…", unsavedChanges: "Unsaved changes", newerVersion: "Newer version exists", allSaved: "All changes saved", draftProtected: "Your draft was not overwritten.", conflictHelp: "Another edit changed this project. Copy your draft or reload the latest version.", reloadLatest: "Reload latest", title: "Title", semanticType: "Semantic type", write: "Write", preview: "Preview", cover: "Cover", attach: "Attach", markdownFormatting: "Markdown formatting", heading: "Heading", bold: "Bold", bulletList: "Bulleted list", writingPlaceholder: "Start with a thought. Markdown is stored as the source of truth.", nothingWritten: "Nothing written yet.", characters: "characters", saveNow: "Save now",
    visualSystem: "Weaver Visual System", createFromTemplate: "Create from a visual template", visualTemplateHint: "Start with a semantic skeleton, projection, layout and theme.", visualViewHint: "Project the same content into another structure without changing the graph.", closeTemplateGallery: "Close template gallery", allVisuals: "All visuals", searchTemplates: "Search templates…", existing: "existing", backToTemplates: "Back to templates", projectTitle: "Project title", goal: "Goal", goalPlaceholder: "What do you want to explore?", scenePack: "Scene Pack", viewName: "View name", viewNamePlaceholder: "Name this perspective", open: "Open", selectTemplate: "Select a template", selectTemplateHint: "Inspect its structure, data requirements, layout and theme before applying it.", checkingData: "Checking current data…", dataReady: "nodes ready for this view", valuesMissing: "required values missing", selectToValidate: "Select to validate current data", missing: "Missing", previewGenerated: "Preview generated at graph r",
    visualGallery: "Visual Template Gallery", existingViews: "existing Views", existingViewsHint: "Open an existing perspective or intentionally create another.", createProject: "Create project", createAnotherView: "Create another View…", createNewView: "Create new View", schemaResetNotice: "Old data was backed up and a new Weaver space was created.", backupLabel: "Backup",
    canvasConnecting: "Connecting Weaver canvas", canvasConnectFailed: "Weaver canvas connection failed", canvasDuplicate: "This canvas is already open in another tab", buildMismatch: "Widget build mismatch", canvasDetached: "This canvas is no longer bound to the current Chat", claimingHelp: "Claiming the canvas session; viewport restoration runs independently.", duplicateHelp: "Use the active Weaver tab. Closing this tab will not affect canvas data.", detachedHelp: "Open Weaver again from the current Chat.", errorCode: "Error code", retryHelp: "You can retry now.", buildMismatchHelp: "Reload using the workspace development entry.",
    edgeStyleBar: "Edge style", lineStyleLabel: "Line style", arrowsLabel: "Arrows", routingLabel: "Routing", solidLine: "Solid", dashedLine: "Dashed", noArrow: "No arrow", singleArrow: "Single arrow", doubleArrow: "Double arrow", straightLine: "Straight", curvedLine: "Curved",
  },
} as const;
export type MessageKey = keyof typeof messages["en-US"];

export function resolveLocale(saved: string | null, languages: readonly string[]): Locale {
  if (saved === "zh-CN" || saved === "en-US") return saved;
  return languages.some((language) => language.toLowerCase().startsWith("zh")) ? "zh-CN" : "en-US";
}

function initialLocale(): Locale { return resolveLocale(localStorage.getItem("weaver.locale"), navigator.languages); }

const I18nContext = createContext<{ locale: Locale; setLocale: (locale: Locale) => void; t: (key: MessageKey) => string } | null>(null);
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, update] = useState<Locale>(initialLocale);
  const value = useMemo(() => ({ locale, setLocale: (next: Locale) => { localStorage.setItem("weaver.locale", next); update(next); }, t: (key: MessageKey) => messages[locale][key] }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error("I18N_PROVIDER_MISSING"); return value; }
