import { registerAppResource, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { McpServer, ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import { getScenePack, builtinScenePacks } from "@weaver/scene-packs";
import { builtinVisualTemplates, getVisualTemplate } from "@weaver/visual-templates";
import { workspaceByProject, workspaceByTask } from "./shared/workspace-registry.js";
import { withStore } from "./shared/tool-runtime.js";
import { bundledWidgetHtml } from "./widget.js";
import type { SseEventHub } from "./event-hub.js";

export type ResourcesCtx = { eventHub: SseEventHub; widgetUri: string };

/** MCP resources: the widget app resource plus declarative reads for scene-packs/templates/tasks/views/assets. */
export function registerResources(server: McpServer, ctx: ResourcesCtx) {
  const { eventHub, widgetUri } = ctx;

  registerAppResource(server, "weaver-workspace-widget", widgetUri, {
    title: "Weaver Semantic Space",
    description: "A native semantic node canvas with natural-language layout tasks and deterministic previews.",
    _meta: {
      ui: { prefersBorder: false, csp: { connectDomains: [eventHub.origin], resourceDomains: ["data:", "blob:"] } },
      "openai/widgetDescription": "Weaver semantic knowledge space",
      "openai/widgetPrefersBorder": false,
    },
  }, async () => ({ contents: [{ uri: widgetUri, mimeType: RESOURCE_MIME_TYPE, text: bundledWidgetHtml(), _meta: { "openai/widgetPrefersBorder": false } }] }));

  server.registerResource("weaver-scene-packs", "weaver://scene-packs", { title: "Weaver Scene Packs", description: "The built-in versioned scene catalog.", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(builtinScenePacks) }] }));
  server.registerResource("weaver-visual-templates", "weaver://visual-templates", { title: "Weaver Visual Templates", description: "The built-in immutable structured visual template catalog.", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(builtinVisualTemplates) }] }));
  server.registerResource("weaver-visual-template", new ResourceTemplate("weaver://visual-templates/{templateId}/{version}", { list: undefined }), { title: "Weaver Visual Template", description: "One versioned VisualTemplate definition.", mimeType: "application/json" }, async (uri, variables) => { const item = getVisualTemplate(String(variables.templateId), String(variables.version)); if (!item) throw new Error("VISUAL_TEMPLATE_NOT_FOUND"); return { contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(item) }] }; });
  server.registerResource("weaver-agent-task", new ResourceTemplate("weaver://agent-tasks/{taskId}", { list: undefined }), { title: "Weaver Agent Task", description: "One persisted AgentTask. Call a task tool first so the server can resolve its workspace.", mimeType: "application/json" }, async (uri, variables) => { const taskId = String(variables.taskId); const workspaceDir = workspaceByTask.get(taskId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_WEAVER_GET_AGENT_TASK_FIRST"); const task = withStore(workspaceDir, (store) => store.getAgentTask(taskId)); if (!task) throw new Error("AGENT_TASK_NOT_FOUND"); return { contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(task) }] }; });
  server.registerResource("weaver-project-views", new ResourceTemplate("weaver://projects/{projectId}/views", { list: undefined }), { title: "Weaver Project Views", description: "Durable saved View catalog records for a project, including recycle-bin state.", mimeType: "application/json" }, async (uri, variables) => { const projectId = String(variables.projectId); const workspaceDir = workspaceByProject.get(projectId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_A_WEAVER_TOOL_FIRST"); const views = withStore(workspaceDir, (store) => store.listProjectViews(projectId)); return { contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(views) }] }; });
  server.registerResource("weaver-view-projection", new ResourceTemplate("weaver://projects/{projectId}/views/{viewId}/projection", { list: undefined }), { title: "Weaver View Projection", description: "Projection and theme metadata for one visual view.", mimeType: "application/json" }, async (uri, variables) => { const projectId = String(variables.projectId); const workspaceDir = workspaceByProject.get(projectId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_A_WEAVER_TOOL_FIRST"); const layout = withStore(workspaceDir, (store) => store.getLayout(projectId, String(variables.viewId))); if (!layout) throw new Error("LAYOUT_NOT_FOUND"); return { contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify({ viewId: layout.viewId, viewName: layout.viewName, viewType: layout.viewType, templateRef: layout.templateRef, projection: layout.projection, theme: layout.theme }) }] }; });
  server.registerResource("weaver-project-manifest", new ResourceTemplate("weaver://projects/{projectId}/manifest", { list: undefined }), { title: "Weaver Project Manifest", description: "Pinned project and scene rules.", mimeType: "application/json" }, async (uri, variables) => { const projectId = String(variables.projectId); const workspaceDir = workspaceByProject.get(projectId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_A_WEAVER_TOOL_FIRST"); const data = withStore(workspaceDir, (store) => { const project = store.getProject(projectId); if (!project) throw new Error("PROJECT_NOT_FOUND"); return { project, scenePack: getScenePack(project.scenePackId, project.scenePackVersion) }; }); return { contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(data) }] }; });
  server.registerResource("weaver-node-content", new ResourceTemplate("weaver://projects/{projectId}/nodes/{nodeId}/content", { list: undefined }), { title: "Weaver Node Content", description: "Full content for one explicitly selected node.", mimeType: "application/json" }, async (uri, variables) => { const projectId = String(variables.projectId); const nodeId = String(variables.nodeId); const workspaceDir = workspaceByProject.get(projectId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_A_WEAVER_TOOL_FIRST"); const node = withStore(workspaceDir, (store) => store.getGraph(projectId).nodes.find((candidate) => candidate.id === nodeId)); if (!node) throw new Error("NODE_NOT_FOUND"); return { contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(node) }] }; });
  server.registerResource("weaver-image-asset", new ResourceTemplate("weaver://projects/{projectId}/assets/{assetId}", { list: undefined }), { title: "Weaver Original Image", description: "Original image bytes for an explicitly requested asset.", mimeType: "application/octet-stream" }, async (uri, variables) => { const projectId = String(variables.projectId); const assetId = String(variables.assetId); const workspaceDir = workspaceByProject.get(projectId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_A_WEAVER_TOOL_FIRST"); const item = withStore(workspaceDir, (store) => store.readAsset(assetId, false)); if (item.asset.projectId !== projectId) throw new Error("ASSET_NOT_FOUND_OR_CROSS_PROJECT"); return { contents: [{ uri: uri.href, mimeType: item.asset.mimeType, blob: Buffer.from(item.data).toString("base64") }] }; });
  server.registerResource("weaver-image-thumbnail", new ResourceTemplate("weaver://projects/{projectId}/assets/{assetId}/thumbnail", { list: undefined }), { title: "Weaver Image Thumbnail", description: "Bounded WebP thumbnail for one image asset.", mimeType: "image/webp" }, async (uri, variables) => { const projectId = String(variables.projectId); const assetId = String(variables.assetId); const workspaceDir = workspaceByProject.get(projectId); if (!workspaceDir) throw new Error("WORKSPACE_UNKNOWN_CALL_A_WEAVER_TOOL_FIRST"); const item = withStore(workspaceDir, (store) => store.readAsset(assetId, true)); if (item.asset.projectId !== projectId) throw new Error("ASSET_NOT_FOUND_OR_CROSS_PROJECT"); return { contents: [{ uri: uri.href, mimeType: "image/webp", blob: Buffer.from(item.data).toString("base64") }] }; });
}
