import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { SseEventHub } from "./event-hub.js";
import { registerResources } from "./resources.js";
import { createMutateWithStore } from "./shared/tool-runtime.js";
import { registerAgentTasksTools } from "./tools/agent-tasks.js";
import { registerArtifactsTools } from "./tools/artifacts.js";
import { registerAssetsTools } from "./tools/assets.js";
import { registerCanvasBindingTools } from "./tools/canvas-binding.js";
import { registerChangesetsTools } from "./tools/changesets.js";
import { registerContentTools } from "./tools/content.js";
import { registerGraphTools } from "./tools/graph.js";
import { registerLayoutTools } from "./tools/layout.js";
import { registerProjectsTools } from "./tools/projects.js";
import { registerTemplatesTools } from "./tools/templates.js";
import { registerViewCatalogTools } from "./tools/view-catalog.js";
import { registerWorkspaceTools } from "./tools/workspace.js";

const manifest = JSON.parse(readFileSync(resolve(process.cwd(), ".codex-plugin", "plugin.json"), "utf8"));
const server = new McpServer({ name: "weaver-mcp-server", version: manifest.version }, { instructions: "Use Weaver tools to create semantic spaces, recommend immutable VisualTemplates, project one content graph into independent views, read concise graph summaries, propose LayoutPlan constraints, and submit auditable ChangeSets. Never invent template ids, final coordinates, or direct asset paths. Applying a template to an existing project must not mutate graph content." });
const eventHub = new SseEventHub();
await eventHub.start();
const widgetUri = "ui://widget/weaver/workspace.html";
const mutateWithStore = createMutateWithStore(eventHub);

registerWorkspaceTools(server, { eventHub, mutateWithStore, widgetUri });
registerProjectsTools(server, { mutateWithStore });
registerTemplatesTools(server, { mutateWithStore });
registerViewCatalogTools(server, { mutateWithStore });
registerGraphTools(server);
registerAssetsTools(server);
registerContentTools(server);
registerCanvasBindingTools(server, { mutateWithStore });
registerAgentTasksTools(server, { mutateWithStore });
registerLayoutTools(server, { eventHub, mutateWithStore });
registerChangesetsTools(server, { mutateWithStore });
registerArtifactsTools(server);
registerResources(server, { eventHub, widgetUri });

const transport = new StdioServerTransport();
for (const signal of ["SIGINT", "SIGTERM"] as const) process.once(signal, () => { void eventHub.close(); });
await server.connect(transport);
const closeTransport = transport.onclose;
transport.onclose = () => { closeTransport?.(); void eventHub.close(); };
