#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONTRACTS_DIR="$ROOT/packages/contracts"
GENERATED_DIR="$CONTRACTS_DIR/generated"
HEADER="// DO NOT EDIT - generated by tooling/codegen/gen-ts.sh"

mkdir -p "$GENERATED_DIR"

"$ROOT/node_modules/.bin/openapi-typescript" "$CONTRACTS_DIR/openapi.json" \
  --output "$GENERATED_DIR/openapi.gen.ts"

tmp_file="$(mktemp)"
{
  printf '%s\n' "$HEADER"
  cat "$GENERATED_DIR/openapi.gen.ts"
} > "$tmp_file"
mv "$tmp_file" "$GENERATED_DIR/openapi.gen.ts"

cat > "$GENERATED_DIR/client.gen.ts" <<'TS'
// DO NOT EDIT - generated by tooling/codegen/gen-ts.sh
import type { paths } from "./openapi.gen";

export type HttpMethod = "get" | "post" | "patch" | "delete";
export type ApiPaths = keyof paths;

export type JsonBody<TPath extends ApiPaths, TMethod extends HttpMethod> =
  TMethod extends keyof paths[TPath]
    ? paths[TPath][TMethod] extends { requestBody: { content: { "application/json": infer TBody } } }
      ? TBody
      : never
    : never;

export type JsonResponse<TPath extends ApiPaths, TMethod extends HttpMethod, TStatus extends number = 200> =
  TMethod extends keyof paths[TPath]
    ? paths[TPath][TMethod] extends { responses: Record<TStatus, { content: { "application/json": infer TResponse } }> }
      ? TResponse
      : never
    : never;
TS

cat > "$GENERATED_DIR/errors.gen.ts" <<'TS'
// DO NOT EDIT - generated by tooling/codegen/gen-ts.sh
export type ErrorCode =
  | "BACKEND_NOT_FOUND"
  | "CYCLE_DETECTED"
  | "DRAFT_NOT_FOUND"
  | "DRAFT_SOURCE_AMBIGUOUS"
  | "EXPORT_NOT_FOUND"
  | "ILLEGAL_STATE_TRANSITION"
  | "INVALID_TREE_OP"
  | "NODE_NOT_FOUND"
  | "QUICKNOTE_NOT_FOUND"
  | "VALIDATION_FAILED";
TS
