import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { changeSetSchema } from "@weaver/contracts";
import { projectSchema, workspaceSchema } from "../shared/schemas.js";
import { defineTool, result, withStore, type MutateWithStore } from "../shared/tool-runtime.js";
import { chatSessionKeyFromRequest } from "../thread-context.js";

export type ChangesetsToolsCtx = { mutateWithStore: MutateWithStore };

/** ChangeSets: submit/apply/list/get/preview/reject auditable graph+layout operation proposals. */
export function registerChangesetsTools(server: McpServer, ctx: ChangesetsToolsCtx) {
  const { mutateWithStore } = ctx;

  server.registerTool("weaver_submit_changeset", { title: "Submit Weaver ChangeSet", description: "Submit structured graph and layout operations for review. Agents cannot write the database directly.", inputSchema: { ...workspaceSchema.shape, changeSet: z.any() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, defineTool(async ({ workspaceDir, changeSet }, extra) => { const chatSessionKey = chatSessionKeyFromRequest(extra); return result(mutateWithStore(workspaceDir, (store) => { const validated = changeSetSchema.parse(changeSet); store.assertTaskChat(validated.taskId, chatSessionKey); return store.submitChangeSet(validated); }), "Submitted ChangeSet."); }));

  server.registerTool("weaver_apply_changeset", { title: "Apply Weaver ChangeSet", description: "Apply one reviewed ChangeSet with graph and per-view layout revision checks.", inputSchema: { ...workspaceSchema.shape, changeSetId: z.string() }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false } }, defineTool(async ({ workspaceDir, changeSetId }, extra) => { const chatSessionKey = chatSessionKeyFromRequest(extra); return result(mutateWithStore(workspaceDir, (store) => { const item = store.getChangeSet(changeSetId); if (!item) throw new Error("CHANGESET_NOT_FOUND"); store.assertTaskChat(item.taskId, chatSessionKey); return store.applyChangeSet(changeSetId); }), "Applied ChangeSet."); }));

  server.registerTool("weaver_list_changesets", { title: "List Weaver ChangeSets", description: "List pending or historical graph/layout proposals for a project.", inputSchema: { ...projectSchema.shape, status: z.enum(["pending", "applied", "rejected", "reverted"]).optional() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, defineTool(async ({ workspaceDir, projectId, status }) => result(withStore(workspaceDir, (store) => store.listChangeSets(projectId, status)))));
  server.registerTool("weaver_get_changeset", { title: "Get Weaver ChangeSet", description: "Read one auditable graph/layout proposal for the current chat-bound task.", inputSchema: { ...workspaceSchema.shape, changeSetId: z.string() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, defineTool(async ({ workspaceDir, changeSetId }, extra) => { const chatSessionKey = chatSessionKeyFromRequest(extra); const item = withStore(workspaceDir, (store) => { const value = store.getChangeSet(changeSetId); if (!value) throw new Error("CHANGESET_NOT_FOUND"); store.assertTaskChat(value.taskId, chatSessionKey, false); return value; }); return result(item); }));
  server.registerTool("weaver_preview_changeset", { title: "Preview Weaver ChangeSet", description: "Return a review-oriented summary and current revision status for one pending ChangeSet.", inputSchema: { ...workspaceSchema.shape, changeSetId: z.string() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, defineTool(async ({ workspaceDir, changeSetId }, extra) => {
    const chatSessionKey = chatSessionKeyFromRequest(extra);
    const preview = withStore(workspaceDir, (store) => { const item = store.getChangeSet(changeSetId); if (!item) throw new Error("CHANGESET_NOT_FOUND"); store.assertTaskChat(item.taskId, chatSessionKey, false); const project = store.getProject(item.projectId); if (!project) throw new Error("PROJECT_NOT_FOUND"); return { changeSet: item, stale: project.graphRevision !== item.baseGraphRevision, currentGraphRevision: project.graphRevision, summary: { addedNodes: item.graphOperations.filter((op) => op.type === "add-node").length, updatedNodes: item.graphOperations.filter((op) => ["update-node", "set-node-content", "attach-asset", "detach-asset", "set-node-cover"].includes(op.type)).length, archivedNodes: item.graphOperations.filter((op) => op.type === "archive-node").length, addedEdges: item.graphOperations.filter((op) => op.type === "add-edge").length, updatedEdges: item.graphOperations.filter((op) => op.type === "update-edge").length, archivedEdges: item.graphOperations.filter((op) => op.type === "archive-edge").length, layoutOperations: item.layoutOperations.length } }; }); return result(preview);
  }));
  server.registerTool("weaver_reject_changeset", { title: "Reject Weaver ChangeSet", description: "Reject one pending proposal without changing graph or layout revisions.", inputSchema: { ...workspaceSchema.shape, changeSetId: z.string() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, defineTool(async ({ workspaceDir, changeSetId }, extra) => { const chatSessionKey = chatSessionKeyFromRequest(extra); return result(mutateWithStore(workspaceDir, (store) => { const item = store.getChangeSet(changeSetId); if (!item) throw new Error("CHANGESET_NOT_FOUND"); store.assertTaskChat(item.taskId, chatSessionKey); return store.rejectChangeSet(changeSetId); })); }));
}
